In [1]:
import pandas as pd, requests

In [5]:
url3 = 'https://raw.githubusercontent.com/chrisc617/Data-Bootcamp'
url4 = '-Final-Project/master/NYC_Transit_Subway_Entrance_And_Exit_Data.csv'
url5 = url3+url4
df=pd.read_csv(url5)
df['geocode_data'] = ''
df['city'] = ''
df['country'] = ''

from geopy.geocoders import Nominatim
geolocator = Nominatim()

In [3]:
def reverse_geocode(latlng):
    result = {}
    url = 'https://maps.googleapis.com/maps/api/geocode/json?latlng={}'
    request = url.format(latlng)
    data = requests.get(request).json()
    if len(data['results']) > 0:
        result = data['results'][0]
    return result

In [4]:
df

,Division,Line,Station Name,Station Latitude,Station Longitude,Route1,Route2,Route3,Route4,Route5,...,North South Street,East West Street,Corner,Entrance Latitude,Entrance Longitude,Station Location,Entrance Location,geocode_data,city,country
0,BMT,4 Avenue,25th St,40.660397,-73.998091,R,NaN,NaN,NaN,NaN,...,4th Ave,25th St,SE,40.660323,-73.997952,"(40.660397, -73.998091)","(40.660323, -73.997952)",,,
1,BMT,4 Avenue,25th St,40.660397,-73.998091,R,NaN,NaN,NaN,NaN,...,4th Ave,25th St,SW,40.660489,-73.998220,"(40.660397, -73.998091)","(40.660489, -73.998220)",,,
2,BMT,4 Avenue,36th St,40.655144,-74.003549,N,R,NaN,NaN,NaN,...,4th Ave,36th St,NW,40.654490,-74.004499,"(40.655144, -74.003549)","(40.654490, -74.004499)",,,

In [8]:
dfbmt=df[df['Division'] == 'BMT']
dfbmt.shape

(442, 35)

In [115]:
dfbmt['Corner'].value_counts()
dfbmtse=dfbmt[dfbmt['Corner'] == 'SE']
dfbmtse

,Division,Line,Station Name,Station Latitude,Station Longitude,Route1,Route2,Route3,Route4,Route5,...,North South Street,East West Street,Corner,Entrance Latitude,Entrance Longitude,Station Location,Entrance Location,geocode_data,city,country
0,BMT,4 Avenue,25th St,40.660397,-73.998091,R,NaN,NaN,NaN,NaN,...,4th Ave,25th St,SE,40.660323,-73.997952,"(40.660397, -73.998091)","(40.660323, -73.997952)",,,
10,BMT,4 Avenue,53rd St,40.645069,-74.014034,R,NaN,NaN,NaN,NaN,...,4th Ave,53rd St,SE,40.644493,-74.014419,"(40.645069, -74.014034)","(40.644493, -74.014419)",,,
12,BMT,4 Avenue,53rd St,40.645069,-74.014034,R,NaN,NaN,NaN,NaN,...,4th Ave,53rd St,SE,40.644601,-74.014309,"(40.645069, -74.014034)","(40.644601, -74.014309)",,,
19,BMT,4 Avenue,59th St,40.641362,-74.017881,N,R,NaN,NaN,NaN,...,4th Ave,60th St,SE,40.640501,-74.018531,"(40.641362, -74.017881)","(40.640501, -74.018531)",,,
24,BMT,4 Avenue,86th St,40.622687,-74.028398,R,NaN,NaN,NaN,NaN,...,4th Ave,86th St,SE,40.622583,-74.028315,"(40.622687, -74.028398)","(40.622583, -74.028315)",,,
37,BMT,4 Avenue,DeKalb Av,40.690635,-73.981824,B,Q,R,NaN,NaN,...,Flatbush Ave,De Kalb Ave,SE,40.689804,-73.981164,"(40.690635, -73.981824)","(40.689804, -73.981164)",,,
39,BMT,4 Avenue,DeKalb Av,40.690635,-73.981824,B,Q,R,NaN,NaN,...,Flatbush Ave,De Kalb Ave,SE,40.689817,-73.981082,"(40.690635, -73.981824)","(40.689817, -73.981082)",,,
40,BMT,4 Avenue,DeKalb Av,40.690635,-73.981824,B,Q,R,NaN,NaN,...,Flatbush Ave,De Kalb Ave,SE,40.689740,-73.981156,"(40.690635, -73.981824)","(40.689740, -73.981156)",,,
47,BMT,4 Avenue,Prospect Av,40.665414,-73.992872,R,NaN,NaN,NaN,NaN,...,4th Ave,Prospect Ave,SE,40.665269,-73.993245,"(40.665414, -73.992872)","(40.665269, -73.993245)",,,
48,BMT,4 Avenue,Union St,40.677316,-73.983110,R,NaN,NaN,NaN,NaN,...,4th Ave,Union St,SE,40.677001,-73.983133,"(40.677316, -73.98311)","(40.677001, -73.983133)",,,
50,BMT,4 Avenue,Union St,40.677316,-73.983110,R,NaN,NaN,NaN,NaN,...,4th Ave,Union St,SE,40.677171,-73.983020,"(40.677316, -73.98311)","(40.677171, -73.983020)",,,
393,BMT,Astoria,30 Av-Grand Av,40.766779,-73.921479,N,Q,NaN,NaN,NaN,...,31st St,30th Ave,SE,40.766700,-73.921406,"(40.766779, -73.921479)","(40.766700, -73.921406)",,,
397,BMT,Astoria,36 Av-Washington Av,40.756804,-73.929575,N,Q,NaN,NaN,NaN,...,31st St,36th Ave,SE,40.756379,-73.929766,"(40.756804, -73.929575)","(40.756379, -73.929766)",,,
400,BMT,Astoria,39 Av-Beebe Av,40.752882,-73.932755,N,Q,NaN,NaN,NaN,...,31st St,39th Ave,SE,40.752491,-73.932936,"(40.752882, -73.932755)","(40.752491, -73.932936)",,,
402,BMT,Astoria,Astoria Blvd-Hoyt Av,40.770258,-73.917843,N,Q,NaN,NaN,NaN,...,31st St,Hoyt Ave South,SE,40.770170,-73.917755,"(40.770258, -73.917843)","(40.770170, -73.917755)",,,
406,BMT,Astoria,Broadway,40.761820,-73.925508,N,Q,NaN,NaN,NaN,...,31st St,Broadway,SE,40.761773,-73.925399,"(40.76182, -73.925508)","(40.761773, -73.925399)",,,
413,BMT,Brighton,7th Av,40.677050,-73.972367,B,Q,NaN,NaN,NaN,...,Carlton Ave,Park Pl,SE,40.677324,-73.972212,"(40.67705, -73.972367)","(40.677324, -73.972212)",,,
416,BMT,Brighton,Av H,40.629270,-73.961639,B,Q,NaN,NaN,NaN,...,15th St,Avenue H,SE,40.629884,-73.961882,"(40.62927, -73.961639)","(40.629884, -73.961882)",,,
417,BMT,Brighton,Av J,40.625039,-73.960803,B,Q,NaN,NaN,NaN,...,15th St,Avenue J,SE,40.625130,-73.960792,"(40.625039, -73.960803)","(40.625130, -73.960792)",,,
420,BMT,Brighton,Av M,40.617618,-73.959399,B,Q,NaN,NaN,NaN,...,15th St,Avenue M,SE,40.617928,-73.959454,"(40.617618, -73.959399)","(40.617928, -73.959454)",,,
422,BMT,Brighton,Av U,40.599300,-73.955929,B,Q,NaN,NaN,NaN,...,15th St,Avenue U,SE,40.598991,-73.955828,"(40.5993, -73.955929)","(40.598991, -73.955828)",,,
423,BMT,Brighton,Beverly Rd,40.644031,-73.964492,B,Q,NaN,NaN,NaN,...,Marlborough Rd,Beverly Rd,SE,40.644272,-73.964528,"(40.644031, -73.964492)","(40.644272, -73.964528)",,,
426,BMT,Brighton,Brighton Beach,40.577621,-73.961376,B,Q,NaN,NaN,NaN,...,Branch 7 St,Brighton Beach Rd,SE,40.577746,-73.960231,"(40.577621, -73.961376)","(40.577746, -73.960231)",,,
427,BMT,Brighton,Brighton Beach,40.577621,-73.961376,B,Q,NaN,NaN,NaN,...,Branch 7 St,Brighton Beach Rd,SE,40.577697,-73.960438,"(40.577621, -73.961376)","(40.577697, -73.960438)",,,
433,BMT,Brighton,Church Av,40.650527,-73.962982,B,Q,NaN,NaN,NaN,...,St. Pauls Pl,Caton Ave,SE,40.651482,-73.962732,"(40.650527, -73.962982)","(40.651482, -73.962732)",,,
434,BMT,Brighton,Cortelyou Rd,40.640927,-73.963891,B,Q,NaN,NaN,NaN,...,Marlborough Rd,Cortelyou Rd,SE,40.641314,-73.963996,"(40.640927, -73.963891)","(40.641314, -73.963996)",,,
435,BMT,Brighton,Kings Highway,40.608670,-73.957734,B,Q,NaN,NaN,NaN,...,15th St,Kings Hwy,SE,40.608835,-73.957769,"(40.60867, -73.957734)","(40.608835, -73.957769)",,,
439,BMT,Brighton,Newkirk Av,40.635082,-73.962793,B,Q,NaN,NaN,NaN,...,Marlborough Rd,Newkirk Ave,SE,40.635034,-73.962736,"(40.635082, -73.962793)","(40.635034, -73.962736)",,,
442,BMT,Brighton,Ocean Parkway,40.576312,-73.968501,Q,NaN,NaN,NaN,NaN,...,Ocean Pkwy,Brighton Beach Rd,SE,40.576209,-73.967875,"(40.576312, -73.968501)","(40.576209, -73.967875)",,,
443,BMT,Brighton,Ocean Parkway,40.576312,-73.968501,Q,NaN,NaN,NaN,NaN,...,Ocean Pkwy,Brighton Beach Rd,SE,40.576234,-73.967561,"(40.576312, -73.968501)","(40.576234, -73.967561)",,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853,BMT,Canarsie,Myrtle Av,40.699814,-73.911586,L,M,NaN,NaN,NaN,...,Palmetto St,Wycoff Ave,SE,40.699807,-73.910999,"(40.699814, -73.911586)","(40.699807, -73.910999)",,,
929,BMT,Coney Island,Stillwell Av,40.577422,-73.981233,D,F,N,Q,NaN,...,Stillwell Ave,Mermaid Ave,SE,40.576900,-73.980846,"(40.577422, -73.981233)","(40.576900, -73.980846)",,,
1445,BMT,Myrtle,Fresh Pond Rd,40.706186,-73.895877,M,NaN,NaN,NaN,NaN,...,Fresh Pond Rd,67th Ave,SE,40.705955,-73.896232,"(40.706186, -73.895877)","(40.705955, -73.896232)",,,
1446,BMT,Myrtle,Fresh Pond Rd,40.706186,-73.895877,M,NaN,NaN,NaN,NaN,...,62nd St,67th Ave,SE,40.706115,-73.895559,"(40.706186, -73.895877)","(40.706115, -73.895559)",,,
1448,BMT,Myrtle,Knickerbocker Av,40.698664,-73.919711,M,NaN,NaN,NaN,NaN,...,Myrtle Ave,Greene Ave,SE,40.698913,-73.918771,"(40.698664, -73.919711)","(40.698913, -73.918771)",,,
1452,BMT,Nassau,Bowery,40.720280,-73.993915,J,Z,NaN,NaN,NaN,...,Bowery,Delancey St,SE,40.719977,-73.993576,"(40.72028, -73.993915)","(40.719977, -73.993576)",,,
1454,BMT,Nassau,Broad St,40.706476,-74.011056,J,Z,NaN,NaN,NaN,...,Broad St,Exchange Pl,SE,40.706142,-74.011128,"(40.706476, -74.011056)","(40.706142, -74.011128)",,,
1455,BMT,Nassau,Broad St,40.706476,-74.011056,J,Z,NaN,NaN,NaN,...,Broad St,Exchange Pl,SE,40.705961,-74.011229,"(40.706476, -74.011056)","(40.705961, -74.011229)",,,
1459,BMT,Nassau,Broad St,40.706476,-74.011056,J,Z,NaN,NaN,NaN,...,Nassau St,Cedar St,SE,40.708027,-74.009814,"(40.706476, -74.011056)","(40.708027, -74.009814)",,,
1460,BMT,Nassau,Broad St,40.706476,-74.011056,J,Z,NaN,NaN,NaN,...,Broad St,Wall St,SE,40.706911,-74.010494,"(40.706476, -74.011056)","(40.706911, -74.010494)",,,
1462,BMT,Nassau,Broad St,40.706476,-74.011056,J,Z,NaN,NaN,NaN,...,Broad St,Wall St,SE,40.706887,-74.010687,"(40.706476, -74.011056)","(40.706887, -74.010687)",,,
1464,BMT,Nassau,Chambers St,40.713243,-74.003401,J,Z,4,5,6,...,Centre St,Chambers St,SE,40.712699,-74.004099,"(40.713243, -74.003401)","(40.712699, -74.004099)",,,
1469,BMT,Nassau,Fulton St,40.710374,-74.007582,A,C,J,Z,2,...,Fulton St,Nassau St,SE,40.710106,-74.007648,"(40.710374, -74.007582)","(40.710106, -74.007648)",,,
1470,BMT,Nassau,Fulton St,40.710374,-74.007582,A,C,J,Z,2,...,John St,Nassau St,SE,40.709376,-74.008375,"(40.710374, -74.007582)","(40.709376, -74.008375)",,,
1744,BMT,Sea Beach,86th St,40.592721,-73.978230,N,NaN,NaN,NaN,NaN,...,8th St,86th St,SE,40.592724,-73.978227,"(40.592721, -73.97823)","(40.592724, -73.978227)",,,
1747,BMT,Sea Beach,Av U,40.597473,-73.979137,N,NaN,NaN,NaN,NaN,...,8th St,Avenue T,SE,40.598512,-73.979335,"(40.597473, -73.979137)","(40.598512, -73.979335)",,,
1748,BMT,Sea Beach,Bay Parkway-22nd Av,40.611815,-73.981848,N,NaN,NaN,NaN,NaN,...,Bay Pkwy,66th St,SE,40.612989,-73.982084,"(40.611815, -73.981848)","(40.612989, -73.982084)",,,
1754,BMT,Sea Beach,New Utrecht Av,40.624842,-73.996353,D,N,NaN,NaN,NaN,...,New Utrecht Ave,62nd St,SE,40.625606,-73.996830,"(40.624842, -73.996353)","(40.625606, -73.996830)",,,
1755,BMT,Sea Beach,New Utrecht Av,40.624842,-73.996353,D,N,NaN,NaN,NaN,...,63rd St,15th Ave,SE,40.624246,-73.995962,"(40.624842, -73.996353)","(40.624246, -73.995962)",,,
1756,BMT,West End,18th Av,40.607954,-74.001736,D,NaN,NaN,NaN,NaN,...,18th Ave,85th St,SE,40.607602,-74.001491,"(40.607954, -74.001736)","(40.607602, -74.001491)",,,
1757,BMT,West End,18th Av,40.607954,-74.001736,D,NaN,NaN,NaN,NaN,...,18th Ave,85th St,SE,40.607723,-74.001894,"(40.607954, -74.001736)","(40.607723, -74.001894)",,,
1759,BMT,West End,20th Av,40.604556,-73.998168,D,NaN,NaN,NaN,NaN,...,20th Ave,86th St,SE,40.604439,-73.998164,"(40.604556, -73.998168)","(40.604439, -73.998164)",,,
1765,BMT,West End,25th Av,40.597704,-73.986829,D,NaN,NaN,NaN,NaN,...,25th Ave,86th St,SE,40.597751,-73.987112,"(40.597704, -73.986829)","(40.597751, -73.987112)",,,
1770,BMT,West End,50th St,40.636260,-73.994791,D,NaN,NaN,NaN,NaN,...,New Utrecht Ave,49th St,SE,40.636405,-73.994673,"(40.63626, -73.994791)","(40.636405, -73.994673)",,,
1771,BMT,West End,55th St,40.631435,-73.995476,D,NaN,NaN,NaN,NaN,...,New Utrecht Ave,55th St,SE,40.631389,-73.995262,"(40.631435, -73.995476)","(40.631389, -73.995262)",,,
1779,BMT,West End,71st St,40.619589,-73.998864,D,NaN,NaN,NaN,NaN,...,New Utrecht Ave,71st St,SE,40.618770,-73.998995,"(40.619589, -73.998864)","(40.618770, -73.998995)",,,
1781,BMT,West End,71st St,40.619589,-73.998864,D,NaN,NaN,NaN,NaN,...,New Utrecht Ave,Bay Ridge Ave,SE,40.620360,-73.998550,"(40.619589, -73.998864)","(40.620360, -73.998550)",,,
1789,BMT,West End,Bay 50th St,40.588841,-73.983765,D,NaN,NaN,NaN,NaN,...,Stillwell Ave,Bay 50th St,SE,40.588066,-73.983498,"(40.588841, -73.983765)","(40.588066, -73.983498)",,,
1791,BMT,West End,Bay 50th St,40.588841,-73.983765,D,NaN,NaN,NaN,NaN,...,Stillwell Ave,Bay 50th St,SE,40.588348,-73.983543,"(40.588841, -73.983765)","(40.588348, -73.983543)",,,
1792,BMT,West End,Bay Parkway,40.601875,-73.993728,D,NaN,NaN,NaN,NaN,...,Bay Pkwy,86th St,SE,40.601726,-73.993696,"(40.601875, -73.993728)","(40.601726, -73.993696)",,,

In [102]:
dfbmt['Route1'].value_counts()

N     92
J     77
L     68
R     57
D     48
B     48
A     20
M     11
F     10
Q      6
FS     3
G      2
Name: Route1, dtype: int64

In [9]:
dfbmt['latlng'] = dfbmt.apply(lambda row: '{},{}'.format(row['Entrance Latitude'], row['Entrance Longitude']), axis=1)
dfbmt['geocode_data'] = dfbmt['latlng'].map(reverse_geocode)
dfbmt['Zip'] =dfbmt['latlng'].apply(geolocator.reverse)
foo = lambda x: pd.Series([i for i in reversed(x.split(','))])
dfbmt['Zip']=dfbmt['Zip'].apply(lambda x: str(x))
dfbmt['Zip']=dfbmt['Zip'].apply(foo)[1]

dfbmt

C:\Users\Chris\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Chris\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Chris\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Chris\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\Chris\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,Division,Line,Station Name,Station Latitude,Station Longitude,Route1,Route2,Route3,Route4,Route5,...,Corner,Entrance Latitude,Entrance Longitude,Station Location,Entrance Location,geocode_data,city,country,latlng,Zip
0,BMT,4 Avenue,25th St,40.660397,-73.998091,R,NaN,NaN,NaN,NaN,...,SE,40.660323,-73.997952,"(40.660397, -73.998091)","(40.660323, -73.997952)",{'address_components': [{'long_name': '749-753...,,,"40.660323,-73.997952",11232
1,BMT,4 Avenue,25th St,40.660397,-73.998091,R,NaN,NaN,NaN,NaN,...,SW,40.660489,-73.998220,"(40.660397, -73.998091)","(40.660489, -73.998220)","{'address_components': [{'long_name': '760', '...",,,"40.660489,-73.99821999999999",11232
2,BMT,4 Avenue,36th St,40.655144,-74.003549,N,R,NaN,NaN,NaN,...,NW,40.654490,-74.004499,"(40.655144, -74.003549)","(40.654490, -74.004499)","{'address_components': [{'long_name': '952', '...",,,"40.65449,-74.004499",11232
3,BMT,4 Avenue,36th St,40.655144,-74.003549,N,R,NaN,NaN,NaN,...,NE,40.654365,-74.004113,"(40.655144, -74.003549)","(40.654365, -74.004113)",{'address_components': [{'long_name': '921-937...,,,"40.654365000000006,-74.004113",11232
4,BMT,4 Avenue,36th St,40.655144,-74.003549,N,R,NaN,NaN,NaN,...,NW,40.654676,-74.004306,"(40.655144, -74.003549)","(40.654676, -74.004306)","{'address_components': [{'long_name': '942', '...",,,"40.654676,-74.004306",11232
5,BMT,4 Avenue,45th St,40.648939,-74.010006,R,NaN,NaN,NaN,NaN,...,NE,40.649389,-74.009333,"(40.648939, -74.010006)","(40.649389, -74.009333)","{'address_components': [{'long_name': '4423', ...",,,"40.649389,-74.009333",11220
6,BMT,4 Avenue,45th St,40.648939,-74.010006,R,NaN,NaN,NaN,NaN,...,NW,40.649424,-74.009728,"(40.648939, -74.010006)","(40.649424, -74.009728)","{'address_components': [{'long_name': '4410', ...",,,"40.649423999999996,-74.00972800000001",11220
7,BMT,4 Avenue,45th St,40.648939,-74.010006,R,NaN,NaN,NaN,NaN,...,NE,40.649265,-74.009457,"(40.648939, -74.010006)","(40.649265, -74.009457)",{'address_components': [{'long_name': '4421-44...,,,"40.649265,-74.009457",11220
8,BMT,4 Avenue,45th St,40.648939,-74.010006,R,NaN,NaN,NaN,NaN,...,NW,40.649546,-74.009602,"(40.648939, -74.010006)","(40.649546, -74.009602)","{'address_components': [{'long_name': '4410', ...",,,"40.649546,-74.009602",11220
9,BMT,4 Avenue,53rd St,40.645069,-74.014034,R,NaN,NaN,NaN,NaN,...,SW,40.644653,-74.014690,"(40.645069, -74.014034)","(40.644653, -74.014690)","{'address_components': [{'long_name': '5314', ...",,,"40.644653000000005,-74.01469",11220
10,BMT,4 Avenue,53rd St,40.645069,-74.014034,R,NaN,NaN,NaN,NaN,...,SE,40.644493,-74.014419,"(40.645069, -74.014034)","(40.644493, -74.014419)","{'address_components': [{'long_name': '5311', ...",,,"40.644493,-74.01441899999999",11220
11,BMT,4 Avenue,53rd St,40.645069,-74.014034,R,NaN,NaN,NaN,NaN,...,SW,40.644756,-74.014586,"(40.645069, -74.014034)","(40.644756, -74.014586)","{'address_components': [{'long_name': '5314', ...",,,"40.644756,-74.014586",11220
12,BMT,4 Avenue,53rd St,40.645069,-74.014034,R,NaN,NaN,NaN,NaN,...,SE,40.644601,-74.014309,"(40.645069, -74.014034)","(40.644601, -74.014309)","{'address_components': [{'long_name': '5301', ...",,,"40.644601,-74.014309",11220
13,BMT,4 Avenue,53rd St,40.645069,-74.014034,R,NaN,NaN,NaN,NaN,...,NW,40.645619,-74.013688,"(40.645069, -74.014034)","(40.645619, -74.013688)","{'address_components': [{'long_name': '5120', ...",,,"40.645619,-74.013688",11220
14,BMT,4 Avenue,59th St,40.641362,-74.017881,N,R,NaN,NaN,NaN,...,NW,40.641606,-74.017897,"(40.641362, -74.017881)","(40.641606, -74.017897)","{'address_components': [{'long_name': '5824', ...",,,"40.641606,-74.01789699999999",11220
15,BMT,4 Avenue,59th St,40.641362,-74.017881,N,R,NaN,NaN,NaN,...,NE,40.641435,-74.017561,"(40.641362, -74.017881)","(40.641435, -74.017561)","{'address_components': [{'long_name': '5823', ...",,,"40.641434999999994,-74.017561",11220
16,BMT,4 Avenue,59th St,40.641362,-74.017881,N,R,NaN,NaN,NaN,...,NW,40.641778,-74.017722,"(40.641362, -74.017881)","(40.641778, -74.017722)","{'address_components': [{'long_name': '5814', ...",,,"40.641778,-74.01772199999999",11220
17,BMT,4 Avenue,59th St,40.641362,-74.017881,N,R,NaN,NaN,NaN,...,NE,40.641633,-74.017362,"(40.641362, -74.017881)","(40.641633, -74.017362)",{'address_components': [{'long_name': '5811-58...,,,"40.641633,-74.017362",11220
18,BMT,4 Avenue,59th St,40.641362,-74.017881,N,R,NaN,NaN,NaN,...,SW,40.640682,-74.018857,"(40.641362, -74.017881)","(40.640682, -74.018857)","{'address_components': [{'long_name': '6012', ...",,,"40.640682,-74.018857",11220
19,BMT,4 Avenue,59th St,40.641362,-74.017881,N,R,NaN,NaN,NaN,...,SE,40.640501,-74.018531,"(40.641362, -74.017881)","(40.640501, -74.018531)","{'address_components': [{'long_name': '6011', ...",,,"40.640501,-74.01853100000001",11220
20,BMT,4 Avenue,77th St,40.629742,-74.025510,R,NaN,NaN,NaN,NaN,...,NW,40.629550,-74.025731,"(40.629742, -74.02551)","(40.629550, -74.025731)","{'address_components': [{'long_name': '7614', ...",,,"40.62955,-74.02573100000001",11209
21,BMT,4 Avenue,77th St,40.629742,-74.025510,R,NaN,NaN,NaN,NaN,...,NE,40.629503,-74.025452,"(40.629742, -74.02551)","(40.629503, -74.025452)",{'address_components': [{'long_name': '7609-76...,,,"40.629503,-74.025452",11209
22,BMT,4 Avenue,77th St,40.629742,-74.025510,R,NaN,NaN,NaN,NaN,...,NW,40.630221,-74.025459,"(40.629742, -74.02551)","(40.630221, -74.025459)","{'address_components': [{'long_name': '7540', ...",,,"40.630221,-74.025459",11209
23,BMT,4 Avenue,86th St,40.622687,-74.028398,R,NaN,NaN,NaN,NaN,...,SW,40.622656,-74.028547,"(40.622687, -74.028398)","(40.622656, -74.028547)",{'address_components': [{'long_name': '8602-86...,,,"40.622656,-74.028547",11209
24,BMT,4 Avenue,86th St,40.622687,-74.028398,R,NaN,NaN,NaN,NaN,...,SE,40.622583,-74.028315,"(40.622687, -74.028398)","(40.622583, -74.028315)","{'address_components': [{'long_name': '8601', ...",,,"40.622583,-74.028315",11209
25,BMT,4 Avenue,86th St,40.622687,-74.028398,R,NaN,NaN,NaN,NaN,...,SW,40.623498,-74.028204,"(40.622687, -74.028398)","(40.623498, -74.028204)","{'address_components': [{'long_name': '8504', ...",,,"40.623498,-74.028204",11209
26,BMT,4 Avenue,95th St,40.616622,-74.030876,R,NaN,NaN,NaN,NaN,...,SW,40.616021,-74.031383,"(40.616622, -74.030876)","(40.616021, -74.031383)","{'address_components': [{'long_name': '9502', ...",,,"40.616021,-74.03138299999999",11209
27,BMT,4 Avenue,95th St,40.616622,-74.030876,R,NaN,NaN,NaN,NaN,...,NE,40.615893,-74.030860,"(40.616622, -74.030876)","(40.615893, -74.030860)","{'address_components': [{'long_name': '9427', ...",,,"40.615893,-74.03086",11209
28,BMT,4 Avenue,95th St,40.616622,-74.030876,R,NaN,NaN,NaN,NaN,...,NW,40.616189,-74.031234,"(40.616622, -74.030876)","(40.616189, -74.031234)",{'address_components': [{'long_name': '371-399...,,,"40.616189,-74.031234",11209
29,BMT,4 Avenue,95th St,40.616622,-74.030876,R,NaN,NaN,NaN,NaN,...,SW,40.617587,-74.030696,"(40.616622, -74.030876)","(40.617587, -74.030696)","{'address_components': [{'long_name': '9302', ...",,,"40.617587,-74.03069599999999",11209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1770,BMT,West End,50th St,40.636260,-73.994791,D,NaN,NaN,NaN,NaN,...,SE,40.636405,-73.994673,"(40.63626, -73.994791)","(40.636405, -73.994673)","{'address_components': [{'long_name': '4901', ...",,,"40.636404999999996,-73.99467299999999",11219
1771,BMT,West End,55th St,40.631435,-73.995476,D,NaN,NaN,NaN,NaN,...,SE,40.631389,-73.995262,"(40.631435, -73.995476)","(40.631389, -73.995262)","{'address_components': [{'long_name': '1312', ...",,,"40.631389,-73.995262",11219
1772,BMT,West End,55th St,40.631435,-73.995476,D,NaN,NaN,NaN,NaN,...,SW,40.631538,-73.995643,"(40.631435, -73.995476)","(40.631538, -73.995643)","{'address_components': [{'long_name': '5501', ...",,,"40.631538,-73.995643",11219
1773,BMT,West End,55th St,40.631435,-73.995476,D,NaN,NaN,NaN,NaN,...,NE,40.631709,-73.995283,"(40.631435, -73.995476)","(40.631709, -73.995283)",{'address_components': [{'long_name': '5415-54...,,,"40.631709,-73.995283",11219
1774,BMT,West End,62nd St,40.626472,-73.996895,D,N,NaN,NaN,NaN,...,NE,40.627299,-73.996465,"(40.626472, -73.996895)","(40.627299, -73.996465)",{'address_components': [{'long_name': '6001-60...,,,"40.627299,-73.996465",11219
1775,BMT,West End,62nd St,40.626472,-73.996895,D,N,NaN,NaN,NaN,...,NW,40.627110,-73.996870,"(40.626472, -73.996895)","(40.627110, -73.996870)","{'address_components': [{'long_name': '6024', ...",,,"40.627109999999995,-73.99687",11219
1776,BMT,West End,62nd St,40.626472,-73.996895,D,N,NaN,NaN,NaN,...,NW,40.627367,-73.996729,"(40.626472, -73.996895)","(40.627367, -73.996729)","{'address_components': [{'long_name': '6014', ...",,,"40.627367,-73.996729",11219
1777,BMT,West End,71st St,40.619589,-73.998864,D,NaN,NaN,NaN,NaN,...,SW,40.618834,-73.999195,"(40.619589, -73.998864)","(40.618834, -73.999195)","{'address_components': [{'long_name': '7104', ...",,,"40.618834,-73.999195",11228
1778,BMT,West End,71st St,40.619589,-73.998864,D,NaN,NaN,NaN,NaN,...,NW,40.619133,-73.999240,"(40.619589, -73.998864)","(40.619133, -73.999240)",{'address_components': [{'long_name': '1551-15...,,,"40.619133000000005,-73.99924",11228
1779,BMT,West End,71st St,40.619589,-73.998864,D,NaN,NaN,NaN,NaN,...,SE,40.618770,-73.998995,"(40.619589, -73.998864)","(40.618770, -73.998995)",{'address_components': [{'long_name': '7101-71...,,,"40.61877,-73.998995",11228
1780,BMT,West End,71st St,40.619589,-73.998864,D,NaN,NaN,NaN,NaN,...,NE,40.618889,-73.998832,"(40.619589, -73.998864)","(40.618889, -73.998832)",{'address_components': [{'long_name': '1575-15...,,,"40.618889,-73.998832",11228
1781,BMT,West End,71st St,40.619589,-73.998864,D,NaN,NaN,NaN,NaN,...,SE,40.620360,-73.998550,"(40.619589, -73.998864)","(40.620360, -73.998550)","{'address_components': [{'long_name': '1548', ...",,,"40.62036,-73.99855",11228
1782,BMT,West End,71st St,40.619589,-73.998864,D,NaN,NaN,NaN,NaN,...,SW,40.620379,-73.998764,"(40.619589, -73.998864)","(40.620379, -73.998764)","{'address_components': [{'long_name': '6904', ...",,,"40.620379,-73.99876400000001",11228
1783,BMT,West End,79th St,40.613501,-74.000610,D,NaN,NaN,NaN,NaN,...,NW,40.612855,-74.000892,"(40.613501, -74.00061)","(40.612855, -74.000892)","{'address_components': [{'long_name': '7826', ...",,,"40.612854999999996,-74.00089200000001",11214
1784,BMT,West End,79th St,40.613501,-74.000610,D,NaN,NaN,NaN,NaN,...,NE,40.612847,-74.000721,"(40.613501, -74.00061)","(40.612847, -74.000721)",{'address_components': [{'long_name': '7805-78...,,,"40.612846999999995,-74.000721",11214
1785,BMT,West End,79th St,40.613501,-74.000610,D,NaN,NaN,NaN,NaN,...,NE,40.614018,-74.000378,"(40.613501, -74.00061)","(40.614018, -74.000378)","{'address_components': [{'long_name': '7625', ...",,,"40.614018,-74.000378",11214
1786,BMT,West End,79th St,40.613501,-74.000610,D,NaN,NaN,NaN,NaN,...,NW,40.614054,-74.000585,"(40.613501, -74.00061)","(40.614054, -74.000585)","{'address_components': [{'long_name': '7704', ...",,,"40.614053999999996,-74.000585",11214
1787,BMT,West End,9th Av,40.646292,-73.994324,D,NaN,NaN,NaN,NaN,...,NE,40.646337,-73.994489,"(40.646292, -73.994324)","(40.646337, -73.994489)",{'address_components': [{'long_name': '3758-38...,,,"40.646337,-73.994489",11219
1788,BMT,West End,Bay 50th St,40.588841,-73.983765,D,NaN,NaN,NaN,NaN,...,SW,40.588022,-73.983735,"(40.588841, -73.983765)","(40.588022, -73.983735)","{'address_components': [{'long_name': '2432', ...",,,"40.588021999999995,-73.983735",11214
1789,BMT,West End,Bay 50th St,40.588841,-73.983765,D,NaN,NaN,NaN,NaN,...,SE,40.588066,-73.983498,"(40.588841, -73.983765)","(40.588066, -73.983498)",{'address_components': [{'long_name': '2431-24...,,,"40.588066,-73.983498",11214
1790,BMT,West End,Bay 50th St,40.588841,-73.983765,D,NaN,NaN,NaN,NaN,...,SW,40.588305,-73.983791,"(40.588841, -73.983765)","(40.588305, -73.983791)","{'address_components': [{'long_name': '2432', ...",,,"40.588305,-73.983791",11214
1791,BMT,West End,Bay 50th St,40.588841,-73.983765,D,NaN,NaN,NaN,NaN,...,SE,40.588348,-73.983543,"(40.588841, -73.983765)","(40.588348, -73.983543)",{'address_components': [{'long_name': '2431-24...,,,"40.588347999999996,-73.98354300000001",11223
1792,BMT,West End,Bay Parkway,40.601875,-73.993728,D,NaN,NaN,NaN,NaN,...,SE,40.601726,-73.993696,"(40.601875, -73.993728)","(40.601726, -73.993696)","{'address_components': [{'long_name': '2202', ...",,,"40.601726,-73.993696",11214
1793,BMT,West End,Bay Parkway,40.601875,-73.993728,D,NaN,NaN,NaN,NaN,...,NE,40.601898,-73.993538,"(40.601875, -73.993728)","(40.601898, -73.993538)","{'address_components': [{'long_name': '2201', ...",,,"40.601898,-73.993538",11214
1794,BMT,West End,Bay Parkway,40.601875,-73.993728,D,NaN,NaN,NaN,NaN,...,SW,40.601993,-73.994130,"(40.601875, -73.993728)","(40.601993, -73.994130)",{'address_components': [{'long_name': '2178-21...,,,"40.601993,-73.99413",11214
1795,BMT,West End,Bay Parkway,40.601875,-73.993728,D,NaN,NaN,NaN,NaN,...,NW,40.602150,-73.993948,"(40.601875, -73.993728)","(40.602150, -73.993948)","{'address_components': [{'long_name': '2173', ...",,,"40.60215,-73.993948",11214
1796,BMT,West End,Fort Hamilton Parkway,40.640914,-73.994304,D,NaN,NaN,NaN,NaN,...,NW,40.640185,-73.994423,"(40.640914, -73.994304)","(40.640185, -73.994423)",{'address_components': [{'long_name': '4406-45...,,,"40.640184999999995,-73.994423",11219
1797,BMT,West End,Fort Hamilton Parkway,40.640914,-73.994304,D,NaN,NaN,NaN,NaN,...,NE,40.640180,-73.994220,"(40.640914, -73.994304)","(40.640180, -73.994220)","{'address_components': [{'long_name': '4409', ...",,,"40.64018,-73.99422",11219
1798,BMT,West End,Fort Hamilton Parkway,40.640914,-73.994304,D,NaN,NaN,NaN,NaN,...,NW,40.641360,-73.994411,"(40.640914, -73.994304)","(40.641360, -73.994411)","{'address_components': [{'long_name': '4320', ...",,,"40.64136,-73.994411",11219
1799,BMT,West End,Fort Hamilton Parkway,40.640914,-73.994304,D,NaN,NaN,NaN,NaN,...,NE,40.641379,-73.994188,"(40.640914, -73.994304)","(40.641379, -73.994188)","{'address_components': [{'long_name': '4305', ...",,,"40.641379,-73.994188",11219

In [10]:
dfbmt

,Division,Line,Station Name,Station Latitude,Station Longitude,Route1,Route2,Route3,Route4,Route5,...,Corner,Entrance Latitude,Entrance Longitude,Station Location,Entrance Location,geocode_data,city,country,latlng,Zip
0,BMT,4 Avenue,25th St,40.660397,-73.998091,R,NaN,NaN,NaN,NaN,...,SE,40.660323,-73.997952,"(40.660397, -73.998091)","(40.660323, -73.997952)",{'address_components': [{'long_name': '749-753...,,,"40.660323,-73.997952",11232
1,BMT,4 Avenue,25th St,40.660397,-73.998091,R,NaN,NaN,NaN,NaN,...,SW,40.660489,-73.998220,"(40.660397, -73.998091)","(40.660489, -73.998220)","{'address_components': [{'long_name': '760', '...",,,"40.660489,-73.99821999999999",11232
2,BMT,4 Avenue,36th St,40.655144,-74.003549,N,R,NaN,NaN,NaN,...,NW,40.654490,-74.004499,"(40.655144, -74.003549)","(40.654490, -74.004499)","{'address_components': [{'long_name': '952', '...",,,"40.65449,-74.004499",11232
3,BMT,4 Avenue,36th St,40.655144,-74.003549,N,R,NaN,NaN,NaN,...,NE,40.654365,-74.004113,"(40.655144, -74.003549)","(40.654365, -74.004113)",{'address_components': [{'long_name': '921-937...,,,"40.654365000000006,-74.004113",11232
4,BMT,4 Avenue,36th St,40.655144,-74.003549,N,R,NaN,NaN,NaN,...,NW,40.654676,-74.004306,"(40.655144, -74.003549)","(40.654676, -74.004306)","{'address_components': [{'long_name': '942', '...",,,"40.654676,-74.004306",11232
5,BMT,4 Avenue,45th St,40.648939,-74.010006,R,NaN,NaN,NaN,NaN,...,NE,40.649389,-74.009333,"(40.648939, -74.010006)","(40.649389, -74.009333)","{'address_components': [{'long_name': '4423', ...",,,"40.649389,-74.009333",11220
6,BMT,4 Avenue,45th St,40.648939,-74.010006,R,NaN,NaN,NaN,NaN,...,NW,40.649424,-74.009728,"(40.648939, -74.010006)","(40.649424, -74.009728)","{'address_components': [{'long_name': '4410', ...",,,"40.649423999999996,-74.00972800000001",11220
7,BMT,4 Avenue,45th St,40.648939,-74.010006,R,NaN,NaN,NaN,NaN,...,NE,40.649265,-74.009457,"(40.648939, -74.010006)","(40.649265, -74.009457)",{'address_components': [{'long_name': '4421-44...,,,"40.649265,-74.009457",11220
8,BMT,4 Avenue,45th St,40.648939,-74.010006,R,NaN,NaN,NaN,NaN,...,NW,40.649546,-74.009602,"(40.648939, -74.010006)","(40.649546, -74.009602)","{'address_components': [{'long_name': '4410', ...",,,"40.649546,-74.009602",11220
9,BMT,4 Avenue,53rd St,40.645069,-74.014034,R,NaN,NaN,NaN,NaN,...,SW,40.644653,-74.014690,"(40.645069, -74.014034)","(40.644653, -74.014690)","{'address_components': [{'long_name': '5314', ...",,,"40.644653000000005,-74.01469",11220
10,BMT,4 Avenue,53rd St,40.645069,-74.014034,R,NaN,NaN,NaN,NaN,...,SE,40.644493,-74.014419,"(40.645069, -74.014034)","(40.644493, -74.014419)","{'address_components': [{'long_name': '5311', ...",,,"40.644493,-74.01441899999999",11220
11,BMT,4 Avenue,53rd St,40.645069,-74.014034,R,NaN,NaN,NaN,NaN,...,SW,40.644756,-74.014586,"(40.645069, -74.014034)","(40.644756, -74.014586)","{'address_components': [{'long_name': '5314', ...",,,"40.644756,-74.014586",11220
12,BMT,4 Avenue,53rd St,40.645069,-74.014034,R,NaN,NaN,NaN,NaN,...,SE,40.644601,-74.014309,"(40.645069, -74.014034)","(40.644601, -74.014309)","{'address_components': [{'long_name': '5301', ...",,,"40.644601,-74.014309",11220
13,BMT,4 Avenue,53rd St,40.645069,-74.014034,R,NaN,NaN,NaN,NaN,...,NW,40.645619,-74.013688,"(40.645069, -74.014034)","(40.645619, -74.013688)","{'address_components': [{'long_name': '5120', ...",,,"40.645619,-74.013688",11220
14,BMT,4 Avenue,59th St,40.641362,-74.017881,N,R,NaN,NaN,NaN,...,NW,40.641606,-74.017897,"(40.641362, -74.017881)","(40.641606, -74.017897)","{'address_components': [{'long_name': '5824', ...",,,"40.641606,-74.01789699999999",11220
15,BMT,4 Avenue,59th St,40.641362,-74.017881,N,R,NaN,NaN,NaN,...,NE,40.641435,-74.017561,"(40.641362, -74.017881)","(40.641435, -74.017561)","{'address_components': [{'long_name': '5823', ...",,,"40.641434999999994,-74.017561",11220
16,BMT,4 Avenue,59th St,40.641362,-74.017881,N,R,NaN,NaN,NaN,...,NW,40.641778,-74.017722,"(40.641362, -74.017881)","(40.641778, -74.017722)","{'address_components': [{'long_name': '5814', ...",,,"40.641778,-74.01772199999999",11220
17,BMT,4 Avenue,59th St,40.641362,-74.017881,N,R,NaN,NaN,NaN,...,NE,40.641633,-74.017362,"(40.641362, -74.017881)","(40.641633, -74.017362)",{'address_components': [{'long_name': '5811-58...,,,"40.641633,-74.017362",11220
18,BMT,4 Avenue,59th St,40.641362,-74.017881,N,R,NaN,NaN,NaN,...,SW,40.640682,-74.018857,"(40.641362, -74.017881)","(40.640682, -74.018857)","{'address_components': [{'long_name': '6012', ...",,,"40.640682,-74.018857",11220
19,BMT,4 Avenue,59th St,40.641362,-74.017881,N,R,NaN,NaN,NaN,...,SE,40.640501,-74.018531,"(40.641362, -74.017881)","(40.640501, -74.018531)","{'address_components': [{'long_name': '6011', ...",,,"40.640501,-74.01853100000001",11220
20,BMT,4 Avenue,77th St,40.629742,-74.025510,R,NaN,NaN,NaN,NaN,...,NW,40.629550,-74.025731,"(40.629742, -74.02551)","(40.629550, -74.025731)","{'address_components': [{'long_name': '7614', ...",,,"40.62955,-74.02573100000001",11209
21,BMT,4 Avenue,77th St,40.629742,-74.025510,R,NaN,NaN,NaN,NaN,...,NE,40.629503,-74.025452,"(40.629742, -74.02551)","(40.629503, -74.025452)",{'address_components': [{'long_name': '7609-76...,,,"40.629503,-74.025452",11209
22,BMT,4 Avenue,77th St,40.629742,-74.025510,R,NaN,NaN,NaN,NaN,...,NW,40.630221,-74.025459,"(40.629742, -74.02551)","(40.630221, -74.025459)","{'address_components': [{'long_name': '7540', ...",,,"40.630221,-74.025459",11209
23,BMT,4 Avenue,86th St,40.622687,-74.028398,R,NaN,NaN,NaN,NaN,...,SW,40.622656,-74.028547,"(40.622687, -74.028398)","(40.622656, -74.028547)",{'address_components': [{'long_name': '8602-86...,,,"40.622656,-74.028547",11209
24,BMT,4 Avenue,86th St,40.622687,-74.028398,R,NaN,NaN,NaN,NaN,...,SE,40.622583,-74.028315,"(40.622687, -74.028398)","(40.622583, -74.028315)","{'address_components': [{'long_name': '8601', ...",,,"40.622583,-74.028315",11209
25,BMT,4 Avenue,86th St,40.622687,-74.028398,R,NaN,NaN,NaN,NaN,...,SW,40.623498,-74.028204,"(40.622687, -74.028398)","(40.623498, -74.028204)","{'address_components': [{'long_name': '8504', ...",,,"40.623498,-74.028204",11209
26,BMT,4 Avenue,95th St,40.616622,-74.030876,R,NaN,NaN,NaN,NaN,...,SW,40.616021,-74.031383,"(40.616622, -74.030876)","(40.616021, -74.031383)","{'address_components': [{'long_name': '9502', ...",,,"40.616021,-74.03138299999999",11209
27,BMT,4 Avenue,95th St,40.616622,-74.030876,R,NaN,NaN,NaN,NaN,...,NE,40.615893,-74.030860,"(40.616622, -74.030876)","(40.615893, -74.030860)","{'address_components': [{'long_name': '9427', ...",,,"40.615893,-74.03086",11209
28,BMT,4 Avenue,95th St,40.616622,-74.030876,R,NaN,NaN,NaN,NaN,...,NW,40.616189,-74.031234,"(40.616622, -74.030876)","(40.616189, -74.031234)",{'address_components': [{'long_name': '371-399...,,,"40.616189,-74.031234",11209
29,BMT,4 Avenue,95th St,40.616622,-74.030876,R,NaN,NaN,NaN,NaN,...,SW,40.617587,-74.030696,"(40.616622, -74.030876)","(40.617587, -74.030696)","{'address_components': [{'long_name': '9302', ...",,,"40.617587,-74.03069599999999",11209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1770,BMT,West End,50th St,40.636260,-73.994791,D,NaN,NaN,NaN,NaN,...,SE,40.636405,-73.994673,"(40.63626, -73.994791)","(40.636405, -73.994673)","{'address_components': [{'long_name': '4901', ...",,,"40.636404999999996,-73.99467299999999",11219
1771,BMT,West End,55th St,40.631435,-73.995476,D,NaN,NaN,NaN,NaN,...,SE,40.631389,-73.995262,"(40.631435, -73.995476)","(40.631389, -73.995262)","{'address_components': [{'long_name': '1312', ...",,,"40.631389,-73.995262",11219
1772,BMT,West End,55th St,40.631435,-73.995476,D,NaN,NaN,NaN,NaN,...,SW,40.631538,-73.995643,"(40.631435, -73.995476)","(40.631538, -73.995643)","{'address_components': [{'long_name': '5501', ...",,,"40.631538,-73.995643",11219
1773,BMT,West End,55th St,40.631435,-73.995476,D,NaN,NaN,NaN,NaN,...,NE,40.631709,-73.995283,"(40.631435, -73.995476)","(40.631709, -73.995283)",{'address_components': [{'long_name': '5415-54...,,,"40.631709,-73.995283",11219
1774,BMT,West End,62nd St,40.626472,-73.996895,D,N,NaN,NaN,NaN,...,NE,40.627299,-73.996465,"(40.626472, -73.996895)","(40.627299, -73.996465)",{'address_components': [{'long_name': '6001-60...,,,"40.627299,-73.996465",11219
1775,BMT,West End,62nd St,40.626472,-73.996895,D,N,NaN,NaN,NaN,...,NW,40.627110,-73.996870,"(40.626472, -73.996895)","(40.627110, -73.996870)","{'address_components': [{'long_name': '6024', ...",,,"40.627109999999995,-73.99687",11219
1776,BMT,West End,62nd St,40.626472,-73.996895,D,N,NaN,NaN,NaN,...,NW,40.627367,-73.996729,"(40.626472, -73.996895)","(40.627367, -73.996729)","{'address_components': [{'long_name': '6014', ...",,,"40.627367,-73.996729",11219
1777,BMT,West End,71st St,40.619589,-73.998864,D,NaN,NaN,NaN,NaN,...,SW,40.618834,-73.999195,"(40.619589, -73.998864)","(40.618834, -73.999195)","{'address_components': [{'long_name': '7104', ...",,,"40.618834,-73.999195",11228
1778,BMT,West End,71st St,40.619589,-73.998864,D,NaN,NaN,NaN,NaN,...,NW,40.619133,-73.999240,"(40.619589, -73.998864)","(40.619133, -73.999240)",{'address_components': [{'long_name': '1551-15...,,,"40.619133000000005,-73.99924",11228
1779,BMT,West End,71st St,40.619589,-73.998864,D,NaN,NaN,NaN,NaN,...,SE,40.618770,-73.998995,"(40.619589, -73.998864)","(40.618770, -73.998995)",{'address_components': [{'long_name': '7101-71...,,,"40.61877,-73.998995",11228
1780,BMT,West End,71st St,40.619589,-73.998864,D,NaN,NaN,NaN,NaN,...,NE,40.618889,-73.998832,"(40.619589, -73.998864)","(40.618889, -73.998832)",{'address_components': [{'long_name': '1575-15...,,,"40.618889,-73.998832",11228
1781,BMT,West End,71st St,40.619589,-73.998864,D,NaN,NaN,NaN,NaN,...,SE,40.620360,-73.998550,"(40.619589, -73.998864)","(40.620360, -73.998550)","{'address_components': [{'long_name': '1548', ...",,,"40.62036,-73.99855",11228
1782,BMT,West End,71st St,40.619589,-73.998864,D,NaN,NaN,NaN,NaN,...,SW,40.620379,-73.998764,"(40.619589, -73.998864)","(40.620379, -73.998764)","{'address_components': [{'long_name': '6904', ...",,,"40.620379,-73.99876400000001",11228
1783,BMT,West End,79th St,40.613501,-74.000610,D,NaN,NaN,NaN,NaN,...,NW,40.612855,-74.000892,"(40.613501, -74.00061)","(40.612855, -74.000892)","{'address_components': [{'long_name': '7826', ...",,,"40.612854999999996,-74.00089200000001",11214
1784,BMT,West End,79th St,40.613501,-74.000610,D,NaN,NaN,NaN,NaN,...,NE,40.612847,-74.000721,"(40.613501, -74.00061)","(40.612847, -74.000721)",{'address_components': [{'long_name': '7805-78...,,,"40.612846999999995,-74.000721",11214
1785,BMT,West End,79th St,40.613501,-74.000610,D,NaN,NaN,NaN,NaN,...,NE,40.614018,-74.000378,"(40.613501, -74.00061)","(40.614018, -74.000378)","{'address_components': [{'long_name': '7625', ...",,,"40.614018,-74.000378",11214
1786,BMT,West End,79th St,40.613501,-74.000610,D,NaN,NaN,NaN,NaN,...,NW,40.614054,-74.000585,"(40.613501, -74.00061)","(40.614054, -74.000585)","{'address_components': [{'long_name': '7704', ...",,,"40.614053999999996,-74.000585",11214
1787,BMT,West End,9th Av,40.646292,-73.994324,D,NaN,NaN,NaN,NaN,...,NE,40.646337,-73.994489,"(40.646292, -73.994324)","(40.646337, -73.994489)",{'address_components': [{'long_name': '3758-38...,,,"40.646337,-73.994489",11219
1788,BMT,West End,Bay 50th St,40.588841,-73.983765,D,NaN,NaN,NaN,NaN,...,SW,40.588022,-73.983735,"(40.588841, -73.983765)","(40.588022, -73.983735)","{'address_components': [{'long_name': '2432', ...",,,"40.588021999999995,-73.983735",11214
1789,BMT,West End,Bay 50th St,40.588841,-73.983765,D,NaN,NaN,NaN,NaN,...,SE,40.588066,-73.983498,"(40.588841, -73.983765)","(40.588066, -73.983498)",{'address_components': [{'long_name': '2431-24...,,,"40.588066,-73.983498",11214
1790,BMT,West End,Bay 50th St,40.588841,-73.983765,D,NaN,NaN,NaN,NaN,...,SW,40.588305,-73.983791,"(40.588841, -73.983765)","(40.588305, -73.983791)","{'address_components': [{'long_name': '2432', ...",,,"40.588305,-73.983791",11214
1791,BMT,West End,Bay 50th St,40.588841,-73.983765,D,NaN,NaN,NaN,NaN,...,SE,40.588348,-73.983543,"(40.588841, -73.983765)","(40.588348, -73.983543)",{'address_components': [{'long_name': '2431-24...,,,"40.588347999999996,-73.98354300000001",11223
1792,BMT,West End,Bay Parkway,40.601875,-73.993728,D,NaN,NaN,NaN,NaN,...,SE,40.601726,-73.993696,"(40.601875, -73.993728)","(40.601726, -73.993696)","{'address_components': [{'long_name': '2202', ...",,,"40.601726,-73.993696",11214
1793,BMT,West End,Bay Parkway,40.601875,-73.993728,D,NaN,NaN,NaN,NaN,...,NE,40.601898,-73.993538,"(40.601875, -73.993728)","(40.601898, -73.993538)","{'address_components': [{'long_name': '2201', ...",,,"40.601898,-73.993538",11214
1794,BMT,West End,Bay Parkway,40.601875,-73.993728,D,NaN,NaN,NaN,NaN,...,SW,40.601993,-73.994130,"(40.601875, -73.993728)","(40.601993, -73.994130)",{'address_components': [{'long_name': '2178-21...,,,"40.601993,-73.99413",11214
1795,BMT,West End,Bay Parkway,40.601875,-73.993728,D,NaN,NaN,NaN,NaN,...,NW,40.602150,-73.993948,"(40.601875, -73.993728)","(40.602150, -73.993948)","{'address_components': [{'long_name': '2173', ...",,,"40.60215,-73.993948",11214
1796,BMT,West End,Fort Hamilton Parkway,40.640914,-73.994304,D,NaN,NaN,NaN,NaN,...,NW,40.640185,-73.994423,"(40.640914, -73.994304)","(40.640185, -73.994423)",{'address_components': [{'long_name': '4406-45...,,,"40.640184999999995,-73.994423",11219
1797,BMT,West End,Fort Hamilton Parkway,40.640914,-73.994304,D,NaN,NaN,NaN,NaN,...,NE,40.640180,-73.994220,"(40.640914, -73.994304)","(40.640180, -73.994220)","{'address_components': [{'long_name': '4409', ...",,,"40.64018,-73.99422",11219
1798,BMT,West End,Fort Hamilton Parkway,40.640914,-73.994304,D,NaN,NaN,NaN,NaN,...,NW,40.641360,-73.994411,"(40.640914, -73.994304)","(40.641360, -73.994411)","{'address_components': [{'long_name': '4320', ...",,,"40.64136,-73.994411",11219
1799,BMT,West End,Fort Hamilton Parkway,40.640914,-73.994304,D,NaN,NaN,NaN,NaN,...,NE,40.641379,-73.994188,"(40.640914, -73.994304)","(40.641379, -73.994188)","{'address_components': [{'long_name': '4305', ...",,,"40.641379,-73.994188",11219